const date = new Date()
console.log(date)

console.log(date.toDateString())
console.log(date.toISOString())
console.log(date.toJSON())
console.log(date.getDate())
console.log(date.getDay())
console.log(date.getFullYear())
console.log(date.getUTCFullYear())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getMonth())
console.log(date.getSeconds())
console.log(date.getMilliseconds())